services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/var/lib/redis/
      - ./logs:/logs
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp | grep 6379 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  fireworks-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fireworks-server
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - redis