server:
  name: fireworks-server
  port: 80

logging:
  config: classpath:log4j2-prod.xml

wechat:
  enabled: false
  app:
    id: <appid>
    secret: <secret>
  authentication:
    token: <token>
    encodingAESKey: <encodingAESKey>

modelProviders:
  openai:
    baseUrl: <baseUrl>
    apiKey: <apiKey>

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      username: <username>
      password: <password>
      connect-timeout: 10s
      timeout: 5s

      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
